# This cannot be in .gitlab-ci-common.yml because the mini-benchmark job is not
# defined on all branches and gitlab ci considers this to be an invalid job.
# Therefore, we can only include this on branches where the mini-benchmark job is defined.
mini-benchmark:
  tags:
    - benchmark

# # This is not yet implemented, but a placeholder and example of what can be done with internal CI.
# mini-benchmark:
#   after_script:
#     - mkdir -p plots
#     # - ./parse_results.py  # Do additional analysis of reported results
#   artifacts:
#     when: always
#     paths:
#       - sysbench-run-*.log
#       # extend artifats with additional plots directory
#       - plots/
#     reports:
#       metrics:
#         - metrics.txt

