# Build stage definitions
.build-template: &build-template
  stage: build
  tags: 
    - arch:amd64
    - size:2xlarge
  variables:
    PARALLEL_PROC: 2
    GIT_STRATEGY: fetch
    GIT_SUBMODULE_STRATEGY: normal
  artifacts:
    when: always
    paths:
      # Must be able to see logs
      - build.log

amazonlinux-2023-build:
  <<: *build-template
  image: amazonlinux:2023
  script:
    # Install packages required for build
    - dnf install -y cmake gcc gcc-c++ openssl-devel ncurses-devel bison zlib-devel
    - dnf install -y https://github.com/stewartsmith/libeatmydata/releases/download/v129/libeatmydata-129-1.fc33.x86_64.rpm
    # Make the build directory
    - mkdir -p builddir && cd builddir
    # Configure the build with cmake
    - cmake $CMAKE_FLAGS -O .. 2>&1 | tee -a ../build.log
    # Accelerate builds with unsafe disk access, as we can afford to loose the entire build anyway
    - eatmydata make package -j $PARALLEL_PROC 2>&1 | tee -a ../build.log
    # - make test # TODO: Takes a very long time. Too long on regular runners.

fedora:
  # override upstream image
  image: fedora:38
  # override upstream runner
  tags: 
    - arch:amd64
    - size:2xlarge

fedora-ninja:
  # override allow failure until https://github.com/MariaDB/server/pull/3026 is merged
  allow_failure: true

# This is not yet implemented, but a placeholder and example of what can be done with internal CI.
mini-benchmark:
  after_script:
    - mkdir -p plots
    # - ./parse_results.py  # Do additional analysis of reported results
  artifacts:
    when: always
    paths:
      - sysbench-run-*.log
      # extend artifats with additional plots directory
      - plots/
    reports:
      metrics:
        - metrics.txt
